<?php
require_once __DIR__ . '/../src/check_admin.php';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アカウント管理</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="header-bar">
        <span>ようこそ、<?php echo htmlspecialchars($_SESSION['user_name']); ?>さん (ロール: <?php echo htmlspecialchars($_SESSION['user_role']); ?>)</span>
        <div>
            <a href="index.php" style="margin-right: 15px;">シフト表に戻る</a>
            <a href="logout.php">ログアウト</a>
        </div>
    </div>

    <div class="container">
        <h1>アカウント管理</h1>
        <div id="controls">
            <button id="add-user-btn">新しいユーザーを追加</button>
        </div>
        <div id="user-list-container">
            <!-- User list table will be generated by JavaScript -->
        </div>
    </div>

    <!-- Add/Edit User Modal -->
    <div id="user-modal" class="modal">
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            <h2 id="modal-title"></h2>
            <form id="user-form">
                <input type="hidden" name="user_id">
                <div class="form-group">
                    <label for="name">氏名:</label>
                    <input type="text" name="name" required>
                </div>
                <div class="form-group">
                    <label for="username">ユーザー名:</label>
                    <input type="text" name="username" required>
                </div>
                <div class="form-group">
                    <label for="role">役割:</label>
                    <select name="role" required>
                        <option value="employee">employee</option>
                        <option value="admin">admin</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="display_order">並び順:</label>
                    <input type="number" name="display_order" value="9999" required>
                    <small>数字が小さいほど上に表示されます。</small>
                </div>
                <div class="form-group">
                    <label for="password">パスワード:</label>
                    <input type="password" name="password">
                    <small>パスワードを変更する場合のみ入力してください。</small>
                </div>
                <button type="submit">保存</button>
            </form>
        </div>
    </div>

    <script src="account_management.js"></script>
</body>
</html>