<?php
require_once __DIR__ . '/../src/check_auth.php';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>シフト管理</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="header-bar">
        <span>ようこそ、<?php echo htmlspecialchars($_SESSION['user_name']); ?>さん (ロール: <?php echo htmlspecialchars($_SESSION['user_role']); ?>)</span>
        <div>
            <?php if ($_SESSION['user_role'] === 'admin'): ?>
                <a href="account_management.php" style="margin-right: 15px;">アカウント管理</a>
            <?php endif; ?>
            <a href="logout.php">ログアウト</a>
        </div>
    </div>
    <div class="container">
        <h1>シフト管理表</h1>

    <div id="nav-controls">
        <button id="prev-month-btn">&lt; 前の月</button>
        <h2 id="current-month-year"></h2>
        <button id="next-month-btn">次の月 &gt;</button>
    </div>
    <div id="period-controls">
        <button id="first-half-btn" class="active">前半 (1-16日)</button>
        <button id="second-half-btn">後半 (17-末日)</button>
    </div>

    <div id="schedule-container">
        <!-- Schedule table will be generated by JavaScript -->
    </div>

    <div id="controls">
        <button id="add-shift-btn">シフトを追加</button>
    </div>
    </div>

    <div id="add-shift-modal" class="modal">
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            <h2>新しいシフト</h2>
            <div id="form-error-message" style="display: none; color: #D8000C; background-color: #FFD2D2; border: 1px solid #D8000C; padding: 10px; border-radius: 5px; margin-bottom: 15px;"></div>
            <form id="add-shift-form">
                <input type="hidden" name="shift_id">
                <div class="form-group">
                    <label for="employee">従業員:</label>
                    <select id="employee" name="employee" required></select>
                </div>
                <div class="form-group">
                    <label for="shift-date">日付:</label>
                    <input type="date" id="shift-date" name="shift-date" required>
                </div>
                <div class="form-group">
                    <label>開始時刻:</label>
                    <div class="time-select-group">
                        <select name="start-hour" required>
                            <option value="00">00</option>
                            <option value="01">01</option>
                            <option value="02">02</option>
                            <option value="03">03</option>
                            <option value="04">04</option>
                            <option value="05">05</option>
                            <option value="06">06</option>
                            <option value="07">07</option>
                            <option value="08">08</option>
                            <option value="09">09</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                            <option value="21">21</option>
                            <option value="22">22</option>
                            <option value="23">23</option>
                        </select>
                        <span>:</span>
                        <select name="start-minute" required>
                            <option value="00">00</option>
                            <option value="30">30</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label>終了時刻:</label>
                    <div class="time-select-group">
                        <select name="end-hour" required>
                            <option value="00">00</option>
                            <option value="01">01</option>
                            <option value="02">02</option>
                            <option value="03">03</option>
                            <option value="04">04</option>
                            <option value="05">05</option>
                            <option value="06">06</option>
                            <option value="07">07</option>
                            <option value="08">08</option>
                            <option value="09">09</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                            <option value="21">21</option>
                            <option value="22">22</option>
                            <option value="23">23</option>
                        </select>
                        <span>:</span>
                        <select name="end-minute" required>
                            <option value="00">00</option>
                            <option value="30">30</option>
                        </select>
                    </div>
                </div>
                <button type="submit">保存</button>
            </form>
        </div>
    </div>

    <script>
        const USER_ROLE = "<?php echo htmlspecialchars($_SESSION['user_role']); ?>";
    </script>
    <script src="script.js"></script>
</body>
</html>