name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # mainブランチにpushされた時に実行

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: /htdocs/   # InfinityFreeの公開フォルダ
          local-dir: ./          # アップロード元ディレクトリ
          protocol: ftp
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.DS_Store
